// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var sextant;
  sextant = function (app) {
    return app.get('/routes', function (req, res) {
      return res.format({
        text: function () {
          return res.send(200, 'routes text');
        },
        json: function () {
          return res.send(200, app.routes);
        }
      });
    });
  };
  module.exports = sextant;
}.call(this);
