// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, first, map, pluck, sextant;
  cache$ = require('underscore');
  first = cache$.first;
  map = cache$.map;
  pluck = cache$.pluck;
  sextant = function (app) {
    app.engine('html', require('ejs').renderFile);
    app.get('/routes', function (req, res) {
      return res.render('' + __dirname + '/../views/routes.html');
    });
    return app.get('/routes.json', function (req, res) {
      var routes, routes_model;
      routes = first(map(app.routes, function (val, key) {
        return val;
      }));
      routes_model = map(routes, function (x) {
        return {
          method: x.method,
          path: x.path,
          params: x.params
        };
      });
      return res.json({
        routes: routes_model,
        app_routes: app.routes
      });
    });
  };
  module.exports = sextant;
}.call(this);
